name: AWS Lambda Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action/@1.1.1
      with:
        args: 
          build hello.bal
    - name: AWS CLI
      uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
      with:
        args: 
          lambda update-function-code --function-name hello --zip-file fileb://aws-ballerina-lambda-functions.zip
      env: 
        AWS_DEFAULT_REGION: us-west-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

