name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Ballerina Build
        uses: ballerina-platform/github-actions/cli/latest@master
        with:
          args: 
            build hello.bal
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          
      - name: GitHub Action for AWS
        uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
        with:
          args: 
            lambda update-function-code --function-name hello --zip-file fileb://aws-ballerina-lambda-functions.zip 

